services:
  toWers:
    build: .
    image: delorenj/towers-mcp-proxy
    container_name: toWers
    restart: unless-stopped
    ports:
      - '${PORT}:3000'
    volumes:
      - toWers-data:/data
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SQLITE_PATH=/data/toWers.db
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mcp.rule=Host(`mcp.delo.sh`)'
      - 'traefik.http.routers.mcp.entrypoints=websecure'
      - 'traefik.http.routers.mcp.tls.certresolver=letsencrypt'
      - 'traefik.http.services.mcp.loadbalancer.server.port=3000'

networks:
  proxy:
    external: true

volumes:
  toWers-data:
    name: toWers-data
