services:
  pluggedin-postgres-dev:
    container_name: pluggedin-postgres-dev
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: pluggedin_dev
      POSTGRES_USER: pluggedin
      POSTGRES_PASSWORD: pluggedin_dev_password
    ports:
      - '5432:5432'
    volumes:
      - pluggedin-postgres-dev:/var/lib/postgresql/data

volumes:
  pluggedin-postgres-dev:
    driver: local
